# Generated by Django 3.0.1 on 2020-01-04 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(max_length=10, unique=True)),
                ('payment_type', models.CharField(choices=[('CREDIT-CARD', 'Credit Card'), ('cash', 'Cash')], default='cash', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('stage', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminpayments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticketpayment', to='tickets.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
