# Generated by Django 3.0.1 on 2020-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('credit-card', 'Credit Card'), ('cash', 'Cash')], default='cash', max_length=12),
        ),
    ]
