# Generated by Django 3.0.1 on 2020-01-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=10, unique=True)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finish', 'Finish')], default='active', max_length=10)),
                ('stage', models.BooleanField(default=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slottickets', to='slots.Slot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
