# Generated by Django 3.0.1 on 2020-01-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_longtime_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='longtime_minutes',
            new_name='longtime',
        ),
    ]
